/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pmsg.proto */

#ifndef PROTOBUF_C_pmsg_2eproto__INCLUDED
#define PROTOBUF_C_pmsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Proto__FingerprintData Proto__FingerprintData;
typedef struct _Proto__CombinedFingerprint Proto__CombinedFingerprint;
typedef struct _Proto__MessageKey Proto__MessageKey;
typedef struct _Proto__SenderKeyDistributionMessage Proto__SenderKeyDistributionMessage;
typedef struct _Proto__ImageMessage Proto__ImageMessage;
typedef struct _Proto__ContactMessage Proto__ContactMessage;
typedef struct _Proto__LocationMessage Proto__LocationMessage;
typedef struct _Proto__ExtendedTextMessage Proto__ExtendedTextMessage;
typedef struct _Proto__DocumentMessage Proto__DocumentMessage;
typedef struct _Proto__AudioMessage Proto__AudioMessage;
typedef struct _Proto__VideoMessage Proto__VideoMessage;
typedef struct _Proto__Call Proto__Call;
typedef struct _Proto__Chat Proto__Chat;
typedef struct _Proto__ProtocolMessage Proto__ProtocolMessage;
typedef struct _Proto__ContactsArrayMessage Proto__ContactsArrayMessage;
typedef struct _Proto__HSMCurrency Proto__HSMCurrency;
typedef struct _Proto__HSMDateTimeComponent Proto__HSMDateTimeComponent;
typedef struct _Proto__HSMDateTimeUnixEpoch Proto__HSMDateTimeUnixEpoch;
typedef struct _Proto__HSMDateTime Proto__HSMDateTime;
typedef struct _Proto__HSMLocalizableParameter Proto__HSMLocalizableParameter;
typedef struct _Proto__HighlyStructuredMessage Proto__HighlyStructuredMessage;
typedef struct _Proto__SendPaymentMessage Proto__SendPaymentMessage;
typedef struct _Proto__RequestPaymentMessage Proto__RequestPaymentMessage;
typedef struct _Proto__LiveLocationMessage Proto__LiveLocationMessage;
typedef struct _Proto__StickerMessage Proto__StickerMessage;
typedef struct _Proto__Message Proto__Message;
typedef struct _Proto__ContextInfo Proto__ContextInfo;
typedef struct _Proto__InteractiveAnnotation Proto__InteractiveAnnotation;
typedef struct _Proto__Point Proto__Point;
typedef struct _Proto__Location Proto__Location;
typedef struct _Proto__WebMessageInfo Proto__WebMessageInfo;
typedef struct _Proto__WebNotificationsInfo Proto__WebNotificationsInfo;
typedef struct _Proto__NotificationMessageInfo Proto__NotificationMessageInfo;
typedef struct _Proto__TabletNotificationsInfo Proto__TabletNotificationsInfo;
typedef struct _Proto__WebFeatures Proto__WebFeatures;


/* --- enums --- */

typedef enum _Proto__ExtendedTextMessage__FONTTYPE {
  PROTO__EXTENDED_TEXT_MESSAGE__FONTTYPE__SANS_SERIF = 0,
  PROTO__EXTENDED_TEXT_MESSAGE__FONTTYPE__SERIF = 1,
  PROTO__EXTENDED_TEXT_MESSAGE__FONTTYPE__NORICAN_REGULAR = 2,
  PROTO__EXTENDED_TEXT_MESSAGE__FONTTYPE__BRYNDAN_WRITE = 3,
  PROTO__EXTENDED_TEXT_MESSAGE__FONTTYPE__BEBASNEUE_REGULAR = 4,
  PROTO__EXTENDED_TEXT_MESSAGE__FONTTYPE__OSWALD_HEAVY = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__EXTENDED_TEXT_MESSAGE__FONTTYPE)
} Proto__ExtendedTextMessage__FONTTYPE;
typedef enum _Proto__VideoMessage__ATTRIBUTION {
  PROTO__VIDEO_MESSAGE__ATTRIBUTION__NONE = 0,
  PROTO__VIDEO_MESSAGE__ATTRIBUTION__GIPHY = 1,
  PROTO__VIDEO_MESSAGE__ATTRIBUTION__TENOR = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__VIDEO_MESSAGE__ATTRIBUTION)
} Proto__VideoMessage__ATTRIBUTION;
typedef enum _Proto__ProtocolMessage__TYPE {
  PROTO__PROTOCOL_MESSAGE__TYPE__REVOKE = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__PROTOCOL_MESSAGE__TYPE)
} Proto__ProtocolMessage__TYPE;
typedef enum _Proto__HSMDateTimeComponent__DAYOFWEEKTYPE {
  PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE__MONDAY = 1,
  PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE__TUESDAY = 2,
  PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE__WEDNESDAY = 3,
  PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE__THURSDAY = 4,
  PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE__FRIDAY = 5,
  PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE__SATURDAY = 6,
  PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE__SUNDAY = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE)
} Proto__HSMDateTimeComponent__DAYOFWEEKTYPE;
typedef enum _Proto__HSMDateTimeComponent__CALENDARTYPE {
  PROTO__HSMDATE_TIME_COMPONENT__CALENDARTYPE__GREGORIAN = 1,
  PROTO__HSMDATE_TIME_COMPONENT__CALENDARTYPE__SOLAR_HIJRI = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__HSMDATE_TIME_COMPONENT__CALENDARTYPE)
} Proto__HSMDateTimeComponent__CALENDARTYPE;
typedef enum _Proto__WebMessageInfo__STATUS {
  PROTO__WEB_MESSAGE_INFO__STATUS__ERROR = 0,
  PROTO__WEB_MESSAGE_INFO__STATUS__PENDING = 1,
  PROTO__WEB_MESSAGE_INFO__STATUS__SERVER_ACK = 2,
  PROTO__WEB_MESSAGE_INFO__STATUS__DELIVERY_ACK = 3,
  PROTO__WEB_MESSAGE_INFO__STATUS__READ = 4,
  PROTO__WEB_MESSAGE_INFO__STATUS__PLAYED = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__WEB_MESSAGE_INFO__STATUS)
} Proto__WebMessageInfo__STATUS;
typedef enum _Proto__WebMessageInfo__STUBTYPE {
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__UNKNOWN = 0,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__REVOKE = 1,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__CIPHERTEXT = 2,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__FUTUREPROOF = 3,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__NON_VERIFIED_TRANSITION = 4,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__UNVERIFIED_TRANSITION = 5,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION = 6,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_LOW_UNKNOWN = 7,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_HIGH = 8,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_INITIAL_UNKNOWN = 9,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_INITIAL_LOW = 10,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_INITIAL_HIGH = 11,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION_ANY_TO_NONE = 12,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION_ANY_TO_HIGH = 13,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION_HIGH_TO_LOW = 14,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION_HIGH_TO_UNKNOWN = 15,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION_UNKNOWN_TO_LOW = 16,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION_LOW_TO_UNKNOWN = 17,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION_NONE_TO_LOW = 18,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__VERIFIED_TRANSITION_NONE_TO_UNKNOWN = 19,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_CREATE = 20,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_CHANGE_SUBJECT = 21,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_CHANGE_ICON = 22,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_CHANGE_INVITE_LINK = 23,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_CHANGE_DESCRIPTION = 24,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_CHANGE_RESTRICT = 25,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_CHANGE_ANNOUNCE = 26,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_PARTICIPANT_ADD = 27,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_PARTICIPANT_REMOVE = 28,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_PARTICIPANT_PROMOTE = 29,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_PARTICIPANT_DEMOTE = 30,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_PARTICIPANT_INVITE = 31,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_PARTICIPANT_LEAVE = 32,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_PARTICIPANT_CHANGE_NUMBER = 33,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__BROADCAST_CREATE = 34,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__BROADCAST_ADD = 35,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__BROADCAST_REMOVE = 36,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GENERIC_NOTIFICATION = 37,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__E2E_IDENTITY_CHANGED = 38,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__E2E_ENCRYPTED = 39,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__CALL_MISSED_VOICE = 40,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__CALL_MISSED_VIDEO = 41,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__INDIVIDUAL_CHANGE_NUMBER = 42,
  PROTO__WEB_MESSAGE_INFO__STUBTYPE__GROUP_DELETE = 43
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__WEB_MESSAGE_INFO__STUBTYPE)
} Proto__WebMessageInfo__STUBTYPE;
typedef enum _Proto__WebFeatures__FLAG {
  PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED = 0,
  PROTO__WEB_FEATURES__FLAG__IMPLEMENTED = 1,
  PROTO__WEB_FEATURES__FLAG__OPTIONAL = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__WEB_FEATURES__FLAG)
} Proto__WebFeatures__FLAG;

/* --- messages --- */

struct  _Proto__FingerprintData
{
  ProtobufCMessage base;
  char *publickey;
  char *identifier;
};
#define PROTO__FINGERPRINT_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__fingerprint_data__descriptor) \
    , NULL, NULL }


struct  _Proto__CombinedFingerprint
{
  ProtobufCMessage base;
  protobuf_c_boolean has_version;
  uint32_t version;
  Proto__FingerprintData *localfingerprint;
  Proto__FingerprintData *remotefingerprint;
};
#define PROTO__COMBINED_FINGERPRINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__combined_fingerprint__descriptor) \
    , 0, 0, NULL, NULL }


struct  _Proto__MessageKey
{
  ProtobufCMessage base;
  char *remotejid;
  protobuf_c_boolean has_fromme;
  protobuf_c_boolean fromme;
  char *id;
  char *participant;
};
#define PROTO__MESSAGE_KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__message_key__descriptor) \
    , NULL, 0, 0, NULL, NULL }


struct  _Proto__SenderKeyDistributionMessage
{
  ProtobufCMessage base;
  char *groupid;
  protobuf_c_boolean has_axolotlsenderkeydistributionmessage;
  ProtobufCBinaryData axolotlsenderkeydistributionmessage;
};
#define PROTO__SENDER_KEY_DISTRIBUTION_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__sender_key_distribution_message__descriptor) \
    , NULL, 0, {0,NULL} }


struct  _Proto__ImageMessage
{
  ProtobufCMessage base;
  char *url;
  char *mimetype;
  char *caption;
  protobuf_c_boolean has_filesha256;
  ProtobufCBinaryData filesha256;
  protobuf_c_boolean has_filelength;
  uint64_t filelength;
  protobuf_c_boolean has_height;
  uint32_t height;
  protobuf_c_boolean has_width;
  uint32_t width;
  protobuf_c_boolean has_mediakey;
  ProtobufCBinaryData mediakey;
  protobuf_c_boolean has_fileencsha256;
  ProtobufCBinaryData fileencsha256;
  size_t n_interactiveannotations;
  Proto__InteractiveAnnotation **interactiveannotations;
  char *directpath;
  protobuf_c_boolean has_jpegthumbnail;
  ProtobufCBinaryData jpegthumbnail;
  Proto__ContextInfo *contextinfo;
  protobuf_c_boolean has_firstscansidecar;
  ProtobufCBinaryData firstscansidecar;
  protobuf_c_boolean has_firstscanlength;
  uint32_t firstscanlength;
};
#define PROTO__IMAGE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__image_message__descriptor) \
    , NULL, NULL, NULL, 0, {0,NULL}, 0, 0, 0, 0, 0, 0, 0, {0,NULL}, 0, {0,NULL}, 0,NULL, NULL, 0, {0,NULL}, NULL, 0, {0,NULL}, 0, 0 }


struct  _Proto__ContactMessage
{
  ProtobufCMessage base;
  char *displayname;
  char *vcard;
  Proto__ContextInfo *contextinfo;
};
#define PROTO__CONTACT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__contact_message__descriptor) \
    , NULL, NULL, NULL }


struct  _Proto__LocationMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_degreeslatitude;
  double degreeslatitude;
  protobuf_c_boolean has_degreeslongitude;
  double degreeslongitude;
  char *name;
  char *address;
  char *url;
  protobuf_c_boolean has_jpegthumbnail;
  ProtobufCBinaryData jpegthumbnail;
  Proto__ContextInfo *contextinfo;
};
#define PROTO__LOCATION_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__location_message__descriptor) \
    , 0, 0, 0, 0, NULL, NULL, NULL, 0, {0,NULL}, NULL }


struct  _Proto__ExtendedTextMessage
{
  ProtobufCMessage base;
  char *text;
  char *matchedtext;
  char *canonicalurl;
  char *description;
  char *title;
  protobuf_c_boolean has_textargb;
  uint32_t textargb;
  protobuf_c_boolean has_backgroundargb;
  uint32_t backgroundargb;
  protobuf_c_boolean has_font;
  Proto__ExtendedTextMessage__FONTTYPE font;
  protobuf_c_boolean has_jpegthumbnail;
  ProtobufCBinaryData jpegthumbnail;
  Proto__ContextInfo *contextinfo;
};
#define PROTO__EXTENDED_TEXT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__extended_text_message__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, PROTO__EXTENDED_TEXT_MESSAGE__FONTTYPE__SANS_SERIF, 0, {0,NULL}, NULL }


struct  _Proto__DocumentMessage
{
  ProtobufCMessage base;
  char *url;
  char *mimetype;
  char *title;
  protobuf_c_boolean has_filesha256;
  ProtobufCBinaryData filesha256;
  protobuf_c_boolean has_filelength;
  uint64_t filelength;
  protobuf_c_boolean has_pagecount;
  uint32_t pagecount;
  protobuf_c_boolean has_mediakey;
  ProtobufCBinaryData mediakey;
  char *filename;
  protobuf_c_boolean has_fileencsha256;
  ProtobufCBinaryData fileencsha256;
  char *directpath;
  protobuf_c_boolean has_jpegthumbnail;
  ProtobufCBinaryData jpegthumbnail;
  Proto__ContextInfo *contextinfo;
};
#define PROTO__DOCUMENT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__document_message__descriptor) \
    , NULL, NULL, NULL, 0, {0,NULL}, 0, 0, 0, 0, 0, {0,NULL}, NULL, 0, {0,NULL}, NULL, 0, {0,NULL}, NULL }


struct  _Proto__AudioMessage
{
  ProtobufCMessage base;
  char *url;
  char *mimetype;
  protobuf_c_boolean has_filesha256;
  ProtobufCBinaryData filesha256;
  protobuf_c_boolean has_filelength;
  uint64_t filelength;
  protobuf_c_boolean has_seconds;
  uint32_t seconds;
  protobuf_c_boolean has_ptt;
  protobuf_c_boolean ptt;
  protobuf_c_boolean has_mediakey;
  ProtobufCBinaryData mediakey;
  protobuf_c_boolean has_fileencsha256;
  ProtobufCBinaryData fileencsha256;
  char *directpath;
  Proto__ContextInfo *contextinfo;
  protobuf_c_boolean has_streamingsidecar;
  ProtobufCBinaryData streamingsidecar;
};
#define PROTO__AUDIO_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__audio_message__descriptor) \
    , NULL, NULL, 0, {0,NULL}, 0, 0, 0, 0, 0, 0, 0, {0,NULL}, 0, {0,NULL}, NULL, NULL, 0, {0,NULL} }


struct  _Proto__VideoMessage
{
  ProtobufCMessage base;
  char *url;
  char *mimetype;
  protobuf_c_boolean has_filesha256;
  ProtobufCBinaryData filesha256;
  protobuf_c_boolean has_filelength;
  uint64_t filelength;
  protobuf_c_boolean has_seconds;
  uint32_t seconds;
  protobuf_c_boolean has_mediakey;
  ProtobufCBinaryData mediakey;
  char *caption;
  protobuf_c_boolean has_gifplayback;
  protobuf_c_boolean gifplayback;
  protobuf_c_boolean has_height;
  uint32_t height;
  protobuf_c_boolean has_width;
  uint32_t width;
  protobuf_c_boolean has_fileencsha256;
  ProtobufCBinaryData fileencsha256;
  size_t n_interactiveannotations;
  Proto__InteractiveAnnotation **interactiveannotations;
  char *directpath;
  protobuf_c_boolean has_jpegthumbnail;
  ProtobufCBinaryData jpegthumbnail;
  Proto__ContextInfo *contextinfo;
  protobuf_c_boolean has_streamingsidecar;
  ProtobufCBinaryData streamingsidecar;
  protobuf_c_boolean has_gifattribution;
  Proto__VideoMessage__ATTRIBUTION gifattribution;
};
#define PROTO__VIDEO_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__video_message__descriptor) \
    , NULL, NULL, 0, {0,NULL}, 0, 0, 0, 0, 0, {0,NULL}, NULL, 0, 0, 0, 0, 0, 0, 0, {0,NULL}, 0,NULL, NULL, 0, {0,NULL}, NULL, 0, {0,NULL}, 0, PROTO__VIDEO_MESSAGE__ATTRIBUTION__NONE }


struct  _Proto__Call
{
  ProtobufCMessage base;
  protobuf_c_boolean has_callkey;
  ProtobufCBinaryData callkey;
};
#define PROTO__CALL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__call__descriptor) \
    , 0, {0,NULL} }


struct  _Proto__Chat
{
  ProtobufCMessage base;
  char *displayname;
  char *id;
};
#define PROTO__CHAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__chat__descriptor) \
    , NULL, NULL }


struct  _Proto__ProtocolMessage
{
  ProtobufCMessage base;
  Proto__MessageKey *key;
  protobuf_c_boolean has_type;
  Proto__ProtocolMessage__TYPE type;
};
#define PROTO__PROTOCOL_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__protocol_message__descriptor) \
    , NULL, 0, PROTO__PROTOCOL_MESSAGE__TYPE__REVOKE }


struct  _Proto__ContactsArrayMessage
{
  ProtobufCMessage base;
  char *displayname;
  size_t n_contacts;
  Proto__ContactMessage **contacts;
  Proto__ContextInfo *contextinfo;
};
#define PROTO__CONTACTS_ARRAY_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__contacts_array_message__descriptor) \
    , NULL, 0,NULL, NULL }


struct  _Proto__HSMCurrency
{
  ProtobufCMessage base;
  char *currencycode;
  protobuf_c_boolean has_amount1000;
  int64_t amount1000;
};
#define PROTO__HSMCURRENCY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__hsmcurrency__descriptor) \
    , NULL, 0, 0 }


struct  _Proto__HSMDateTimeComponent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_dayofweek;
  Proto__HSMDateTimeComponent__DAYOFWEEKTYPE dayofweek;
  protobuf_c_boolean has_year;
  uint32_t year;
  protobuf_c_boolean has_month;
  uint32_t month;
  protobuf_c_boolean has_dayofmonth;
  uint32_t dayofmonth;
  protobuf_c_boolean has_hour;
  uint32_t hour;
  protobuf_c_boolean has_minute;
  uint32_t minute;
  protobuf_c_boolean has_calendar;
  Proto__HSMDateTimeComponent__CALENDARTYPE calendar;
};
#define PROTO__HSMDATE_TIME_COMPONENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__hsmdate_time_component__descriptor) \
    , 0, PROTO__HSMDATE_TIME_COMPONENT__DAYOFWEEKTYPE__MONDAY, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, PROTO__HSMDATE_TIME_COMPONENT__CALENDARTYPE__GREGORIAN }


struct  _Proto__HSMDateTimeUnixEpoch
{
  ProtobufCMessage base;
  protobuf_c_boolean has_timestamp;
  int64_t timestamp;
};
#define PROTO__HSMDATE_TIME_UNIX_EPOCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__hsmdate_time_unix_epoch__descriptor) \
    , 0, 0 }


typedef enum {
  PROTO__HSMDATE_TIME__DATETIME_ONEOF__NOT_SET = 0,
  PROTO__HSMDATE_TIME__DATETIME_ONEOF_COMPONENT = 1,
  PROTO__HSMDATE_TIME__DATETIME_ONEOF_UNIX_EPOCH = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__HSMDATE_TIME__DATETIME_ONEOF)
} Proto__HSMDateTime__DatetimeOneofCase;

struct  _Proto__HSMDateTime
{
  ProtobufCMessage base;
  Proto__HSMDateTime__DatetimeOneofCase datetime_oneof_case;
  union {
    Proto__HSMDateTimeComponent *component;
    Proto__HSMDateTimeUnixEpoch *unixepoch;
  };
};
#define PROTO__HSMDATE_TIME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__hsmdate_time__descriptor) \
    , PROTO__HSMDATE_TIME__DATETIME_ONEOF__NOT_SET, {0} }


typedef enum {
  PROTO__HSMLOCALIZABLE_PARAMETER__PARAM_ONEOF__NOT_SET = 0,
  PROTO__HSMLOCALIZABLE_PARAMETER__PARAM_ONEOF_CURRENCY = 2,
  PROTO__HSMLOCALIZABLE_PARAMETER__PARAM_ONEOF_DATE_TIME = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__HSMLOCALIZABLE_PARAMETER__PARAM_ONEOF)
} Proto__HSMLocalizableParameter__ParamOneofCase;

struct  _Proto__HSMLocalizableParameter
{
  ProtobufCMessage base;
  char *default_;
  Proto__HSMLocalizableParameter__ParamOneofCase param_oneof_case;
  union {
    Proto__HSMCurrency *currency;
    Proto__HSMDateTime *datetime;
  };
};
#define PROTO__HSMLOCALIZABLE_PARAMETER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__hsmlocalizable_parameter__descriptor) \
    , NULL, PROTO__HSMLOCALIZABLE_PARAMETER__PARAM_ONEOF__NOT_SET, {0} }


struct  _Proto__HighlyStructuredMessage
{
  ProtobufCMessage base;
  char *namespace_;
  char *elementname;
  size_t n_params;
  char **params;
  char *fallbacklg;
  char *fallbacklc;
  size_t n_localizableparams;
  Proto__HSMLocalizableParameter **localizableparams;
};
#define PROTO__HIGHLY_STRUCTURED_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__highly_structured_message__descriptor) \
    , NULL, NULL, 0,NULL, NULL, NULL, 0,NULL }


struct  _Proto__SendPaymentMessage
{
  ProtobufCMessage base;
  Proto__Message *notemessage;
};
#define PROTO__SEND_PAYMENT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__send_payment_message__descriptor) \
    , NULL }


struct  _Proto__RequestPaymentMessage
{
  ProtobufCMessage base;
  char *currencycodeiso4217;
  protobuf_c_boolean has_amount1000;
  uint64_t amount1000;
  char *requestfrom;
  Proto__Message *notemessage;
};
#define PROTO__REQUEST_PAYMENT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__request_payment_message__descriptor) \
    , NULL, 0, 0, NULL, NULL }


struct  _Proto__LiveLocationMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_degreeslatitude;
  double degreeslatitude;
  protobuf_c_boolean has_degreeslongitude;
  double degreeslongitude;
  protobuf_c_boolean has_accuracyinmeters;
  uint32_t accuracyinmeters;
  protobuf_c_boolean has_speedinmps;
  float speedinmps;
  protobuf_c_boolean has_degreesclockwisefrommagneticnorth;
  uint32_t degreesclockwisefrommagneticnorth;
  char *caption;
  protobuf_c_boolean has_sequencenumber;
  int64_t sequencenumber;
  protobuf_c_boolean has_jpegthumbnail;
  ProtobufCBinaryData jpegthumbnail;
  Proto__ContextInfo *contextinfo;
};
#define PROTO__LIVE_LOCATION_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__live_location_message__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, {0,NULL}, NULL }


struct  _Proto__StickerMessage
{
  ProtobufCMessage base;
  char *url;
  protobuf_c_boolean has_filesha256;
  ProtobufCBinaryData filesha256;
  protobuf_c_boolean has_fileencsha256;
  ProtobufCBinaryData fileencsha256;
  protobuf_c_boolean has_mediakey;
  ProtobufCBinaryData mediakey;
  char *mimetype;
  protobuf_c_boolean has_height;
  uint32_t height;
  protobuf_c_boolean has_width;
  uint32_t width;
  char *directpath;
  protobuf_c_boolean has_filelength;
  uint64_t filelength;
  protobuf_c_boolean has_pngthumbnail;
  ProtobufCBinaryData pngthumbnail;
  Proto__ContextInfo *contextinfo;
};
#define PROTO__STICKER_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__sticker_message__descriptor) \
    , NULL, 0, {0,NULL}, 0, {0,NULL}, 0, {0,NULL}, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, {0,NULL}, NULL }


struct  _Proto__Message
{
  ProtobufCMessage base;
  char *conversation;
  Proto__SenderKeyDistributionMessage *senderkeydistributionmessage;
  Proto__ImageMessage *imagemessage;
  Proto__ContactMessage *contactmessage;
  Proto__LocationMessage *locationmessage;
  Proto__ExtendedTextMessage *extendedtextmessage;
  Proto__DocumentMessage *documentmessage;
  Proto__AudioMessage *audiomessage;
  Proto__VideoMessage *videomessage;
  Proto__Call *call;
  Proto__Chat *chat;
  Proto__ProtocolMessage *protocolmessage;
  Proto__ContactsArrayMessage *contactsarraymessage;
  Proto__HighlyStructuredMessage *highlystructuredmessage;
  Proto__SenderKeyDistributionMessage *fastratchetkeysenderkeydistributionmessage;
  Proto__SendPaymentMessage *sendpaymentmessage;
  Proto__RequestPaymentMessage *requestpaymentmessage;
  Proto__LiveLocationMessage *livelocationmessage;
  Proto__StickerMessage *stickermessage;
};
#define PROTO__MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__message__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _Proto__ContextInfo
{
  ProtobufCMessage base;
  char *stanzaid;
  char *participant;
  size_t n_quotedmessage;
  Proto__Message **quotedmessage;
  char *remotejid;
  size_t n_mentionedjid;
  char **mentionedjid;
  char *conversionsource;
  protobuf_c_boolean has_conversiondata;
  ProtobufCBinaryData conversiondata;
  protobuf_c_boolean has_conversiondelayseconds;
  uint32_t conversiondelayseconds;
  protobuf_c_boolean has_isforwarded;
  protobuf_c_boolean isforwarded;
};
#define PROTO__CONTEXT_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__context_info__descriptor) \
    , NULL, NULL, 0,NULL, NULL, 0,NULL, NULL, 0, {0,NULL}, 0, 0, 0, 0 }


typedef enum {
  PROTO__INTERACTIVE_ANNOTATION__ACTION__NOT_SET = 0,
  PROTO__INTERACTIVE_ANNOTATION__ACTION_LOCATION = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__INTERACTIVE_ANNOTATION__ACTION)
} Proto__InteractiveAnnotation__ActionCase;

struct  _Proto__InteractiveAnnotation
{
  ProtobufCMessage base;
  size_t n_polygonvertices;
  Proto__Point **polygonvertices;
  Proto__InteractiveAnnotation__ActionCase action_case;
  union {
    Proto__Location *location;
  };
};
#define PROTO__INTERACTIVE_ANNOTATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__interactive_annotation__descriptor) \
    , 0,NULL, PROTO__INTERACTIVE_ANNOTATION__ACTION__NOT_SET, {0} }


struct  _Proto__Point
{
  ProtobufCMessage base;
  protobuf_c_boolean has_x;
  double x;
  protobuf_c_boolean has_y;
  double y;
};
#define PROTO__POINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__point__descriptor) \
    , 0, 0, 0, 0 }


struct  _Proto__Location
{
  ProtobufCMessage base;
  protobuf_c_boolean has_degreeslatitude;
  double degreeslatitude;
  protobuf_c_boolean has_degreeslongitude;
  double degreeslongitude;
  char *name;
};
#define PROTO__LOCATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__location__descriptor) \
    , 0, 0, 0, 0, NULL }


struct  _Proto__WebMessageInfo
{
  ProtobufCMessage base;
  Proto__MessageKey *key;
  Proto__Message *message;
  protobuf_c_boolean has_messagetimestamp;
  uint64_t messagetimestamp;
  protobuf_c_boolean has_status;
  Proto__WebMessageInfo__STATUS status;
  char *participant;
  protobuf_c_boolean has_ignore;
  protobuf_c_boolean ignore;
  protobuf_c_boolean has_starred;
  protobuf_c_boolean starred;
  protobuf_c_boolean has_broadcast;
  protobuf_c_boolean broadcast;
  char *pushname;
  protobuf_c_boolean has_mediaciphertextsha256;
  ProtobufCBinaryData mediaciphertextsha256;
  protobuf_c_boolean has_multicast;
  protobuf_c_boolean multicast;
  protobuf_c_boolean has_urltext;
  protobuf_c_boolean urltext;
  protobuf_c_boolean has_urlnumber;
  protobuf_c_boolean urlnumber;
  protobuf_c_boolean has_messagestubtype;
  Proto__WebMessageInfo__STUBTYPE messagestubtype;
  protobuf_c_boolean has_clearmedia;
  protobuf_c_boolean clearmedia;
  size_t n_messagestubparameters;
  char **messagestubparameters;
  protobuf_c_boolean has_duration;
  uint32_t duration;
  size_t n_labels;
  char **labels;
};
#define PROTO__WEB_MESSAGE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__web_message_info__descriptor) \
    , NULL, NULL, 0, 0, 0, PROTO__WEB_MESSAGE_INFO__STATUS__PENDING, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, {0,NULL}, 0, 0, 0, 0, 0, 0, 0, PROTO__WEB_MESSAGE_INFO__STUBTYPE__UNKNOWN, 0, 0, 0,NULL, 0, 0, 0,NULL }


struct  _Proto__WebNotificationsInfo
{
  ProtobufCMessage base;
  protobuf_c_boolean has_timestamp;
  uint64_t timestamp;
  protobuf_c_boolean has_unreadchats;
  uint32_t unreadchats;
  protobuf_c_boolean has_notifymessagecount;
  uint32_t notifymessagecount;
  size_t n_notifymessages;
  Proto__Message **notifymessages;
};
#define PROTO__WEB_NOTIFICATIONS_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__web_notifications_info__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0,NULL }


struct  _Proto__NotificationMessageInfo
{
  ProtobufCMessage base;
  Proto__MessageKey *key;
  Proto__Message *message;
  protobuf_c_boolean has_messagetimestamp;
  uint64_t messagetimestamp;
  char *participant;
};
#define PROTO__NOTIFICATION_MESSAGE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__notification_message_info__descriptor) \
    , NULL, NULL, 0, 0, NULL }


struct  _Proto__TabletNotificationsInfo
{
  ProtobufCMessage base;
  protobuf_c_boolean has_timestamp;
  uint64_t timestamp;
  protobuf_c_boolean has_unreadchats;
  uint32_t unreadchats;
  protobuf_c_boolean has_notifymessagecount;
  uint32_t notifymessagecount;
  size_t n_notifymessage;
  Proto__Message **notifymessage;
};
#define PROTO__TABLET_NOTIFICATIONS_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__tablet_notifications_info__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0,NULL }


struct  _Proto__WebFeatures
{
  ProtobufCMessage base;
  protobuf_c_boolean has_labelsdisplay;
  Proto__WebFeatures__FLAG labelsdisplay;
  protobuf_c_boolean has_voipindividualoutgoing;
  Proto__WebFeatures__FLAG voipindividualoutgoing;
  protobuf_c_boolean has_groupsv3;
  Proto__WebFeatures__FLAG groupsv3;
  protobuf_c_boolean has_groupsv3create;
  Proto__WebFeatures__FLAG groupsv3create;
  protobuf_c_boolean has_changenumberv2;
  Proto__WebFeatures__FLAG changenumberv2;
  protobuf_c_boolean has_querystatusv3thumbnail;
  Proto__WebFeatures__FLAG querystatusv3thumbnail;
  protobuf_c_boolean has_livelocations;
  Proto__WebFeatures__FLAG livelocations;
  protobuf_c_boolean has_queryvname;
  Proto__WebFeatures__FLAG queryvname;
  protobuf_c_boolean has_voipindividualincoming;
  Proto__WebFeatures__FLAG voipindividualincoming;
  protobuf_c_boolean has_quickrepliesquery;
  Proto__WebFeatures__FLAG quickrepliesquery;
};
#define PROTO__WEB_FEATURES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__web_features__descriptor) \
    , 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED, 0, PROTO__WEB_FEATURES__FLAG__NOT_IMPLEMENTED }


/* Proto__FingerprintData methods */
void   proto__fingerprint_data__init
                     (Proto__FingerprintData         *message);
size_t proto__fingerprint_data__get_packed_size
                     (const Proto__FingerprintData   *message);
size_t proto__fingerprint_data__pack
                     (const Proto__FingerprintData   *message,
                      uint8_t             *out);
size_t proto__fingerprint_data__pack_to_buffer
                     (const Proto__FingerprintData   *message,
                      ProtobufCBuffer     *buffer);
Proto__FingerprintData *
       proto__fingerprint_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__fingerprint_data__free_unpacked
                     (Proto__FingerprintData *message,
                      ProtobufCAllocator *allocator);
/* Proto__CombinedFingerprint methods */
void   proto__combined_fingerprint__init
                     (Proto__CombinedFingerprint         *message);
size_t proto__combined_fingerprint__get_packed_size
                     (const Proto__CombinedFingerprint   *message);
size_t proto__combined_fingerprint__pack
                     (const Proto__CombinedFingerprint   *message,
                      uint8_t             *out);
size_t proto__combined_fingerprint__pack_to_buffer
                     (const Proto__CombinedFingerprint   *message,
                      ProtobufCBuffer     *buffer);
Proto__CombinedFingerprint *
       proto__combined_fingerprint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__combined_fingerprint__free_unpacked
                     (Proto__CombinedFingerprint *message,
                      ProtobufCAllocator *allocator);
/* Proto__MessageKey methods */
void   proto__message_key__init
                     (Proto__MessageKey         *message);
size_t proto__message_key__get_packed_size
                     (const Proto__MessageKey   *message);
size_t proto__message_key__pack
                     (const Proto__MessageKey   *message,
                      uint8_t             *out);
size_t proto__message_key__pack_to_buffer
                     (const Proto__MessageKey   *message,
                      ProtobufCBuffer     *buffer);
Proto__MessageKey *
       proto__message_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__message_key__free_unpacked
                     (Proto__MessageKey *message,
                      ProtobufCAllocator *allocator);
/* Proto__SenderKeyDistributionMessage methods */
void   proto__sender_key_distribution_message__init
                     (Proto__SenderKeyDistributionMessage         *message);
size_t proto__sender_key_distribution_message__get_packed_size
                     (const Proto__SenderKeyDistributionMessage   *message);
size_t proto__sender_key_distribution_message__pack
                     (const Proto__SenderKeyDistributionMessage   *message,
                      uint8_t             *out);
size_t proto__sender_key_distribution_message__pack_to_buffer
                     (const Proto__SenderKeyDistributionMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__SenderKeyDistributionMessage *
       proto__sender_key_distribution_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__sender_key_distribution_message__free_unpacked
                     (Proto__SenderKeyDistributionMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__ImageMessage methods */
void   proto__image_message__init
                     (Proto__ImageMessage         *message);
size_t proto__image_message__get_packed_size
                     (const Proto__ImageMessage   *message);
size_t proto__image_message__pack
                     (const Proto__ImageMessage   *message,
                      uint8_t             *out);
size_t proto__image_message__pack_to_buffer
                     (const Proto__ImageMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__ImageMessage *
       proto__image_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__image_message__free_unpacked
                     (Proto__ImageMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__ContactMessage methods */
void   proto__contact_message__init
                     (Proto__ContactMessage         *message);
size_t proto__contact_message__get_packed_size
                     (const Proto__ContactMessage   *message);
size_t proto__contact_message__pack
                     (const Proto__ContactMessage   *message,
                      uint8_t             *out);
size_t proto__contact_message__pack_to_buffer
                     (const Proto__ContactMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__ContactMessage *
       proto__contact_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__contact_message__free_unpacked
                     (Proto__ContactMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__LocationMessage methods */
void   proto__location_message__init
                     (Proto__LocationMessage         *message);
size_t proto__location_message__get_packed_size
                     (const Proto__LocationMessage   *message);
size_t proto__location_message__pack
                     (const Proto__LocationMessage   *message,
                      uint8_t             *out);
size_t proto__location_message__pack_to_buffer
                     (const Proto__LocationMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__LocationMessage *
       proto__location_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__location_message__free_unpacked
                     (Proto__LocationMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__ExtendedTextMessage methods */
void   proto__extended_text_message__init
                     (Proto__ExtendedTextMessage         *message);
size_t proto__extended_text_message__get_packed_size
                     (const Proto__ExtendedTextMessage   *message);
size_t proto__extended_text_message__pack
                     (const Proto__ExtendedTextMessage   *message,
                      uint8_t             *out);
size_t proto__extended_text_message__pack_to_buffer
                     (const Proto__ExtendedTextMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__ExtendedTextMessage *
       proto__extended_text_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__extended_text_message__free_unpacked
                     (Proto__ExtendedTextMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__DocumentMessage methods */
void   proto__document_message__init
                     (Proto__DocumentMessage         *message);
size_t proto__document_message__get_packed_size
                     (const Proto__DocumentMessage   *message);
size_t proto__document_message__pack
                     (const Proto__DocumentMessage   *message,
                      uint8_t             *out);
size_t proto__document_message__pack_to_buffer
                     (const Proto__DocumentMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__DocumentMessage *
       proto__document_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__document_message__free_unpacked
                     (Proto__DocumentMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__AudioMessage methods */
void   proto__audio_message__init
                     (Proto__AudioMessage         *message);
size_t proto__audio_message__get_packed_size
                     (const Proto__AudioMessage   *message);
size_t proto__audio_message__pack
                     (const Proto__AudioMessage   *message,
                      uint8_t             *out);
size_t proto__audio_message__pack_to_buffer
                     (const Proto__AudioMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__AudioMessage *
       proto__audio_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__audio_message__free_unpacked
                     (Proto__AudioMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__VideoMessage methods */
void   proto__video_message__init
                     (Proto__VideoMessage         *message);
size_t proto__video_message__get_packed_size
                     (const Proto__VideoMessage   *message);
size_t proto__video_message__pack
                     (const Proto__VideoMessage   *message,
                      uint8_t             *out);
size_t proto__video_message__pack_to_buffer
                     (const Proto__VideoMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__VideoMessage *
       proto__video_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__video_message__free_unpacked
                     (Proto__VideoMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__Call methods */
void   proto__call__init
                     (Proto__Call         *message);
size_t proto__call__get_packed_size
                     (const Proto__Call   *message);
size_t proto__call__pack
                     (const Proto__Call   *message,
                      uint8_t             *out);
size_t proto__call__pack_to_buffer
                     (const Proto__Call   *message,
                      ProtobufCBuffer     *buffer);
Proto__Call *
       proto__call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__call__free_unpacked
                     (Proto__Call *message,
                      ProtobufCAllocator *allocator);
/* Proto__Chat methods */
void   proto__chat__init
                     (Proto__Chat         *message);
size_t proto__chat__get_packed_size
                     (const Proto__Chat   *message);
size_t proto__chat__pack
                     (const Proto__Chat   *message,
                      uint8_t             *out);
size_t proto__chat__pack_to_buffer
                     (const Proto__Chat   *message,
                      ProtobufCBuffer     *buffer);
Proto__Chat *
       proto__chat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__chat__free_unpacked
                     (Proto__Chat *message,
                      ProtobufCAllocator *allocator);
/* Proto__ProtocolMessage methods */
void   proto__protocol_message__init
                     (Proto__ProtocolMessage         *message);
size_t proto__protocol_message__get_packed_size
                     (const Proto__ProtocolMessage   *message);
size_t proto__protocol_message__pack
                     (const Proto__ProtocolMessage   *message,
                      uint8_t             *out);
size_t proto__protocol_message__pack_to_buffer
                     (const Proto__ProtocolMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__ProtocolMessage *
       proto__protocol_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__protocol_message__free_unpacked
                     (Proto__ProtocolMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__ContactsArrayMessage methods */
void   proto__contacts_array_message__init
                     (Proto__ContactsArrayMessage         *message);
size_t proto__contacts_array_message__get_packed_size
                     (const Proto__ContactsArrayMessage   *message);
size_t proto__contacts_array_message__pack
                     (const Proto__ContactsArrayMessage   *message,
                      uint8_t             *out);
size_t proto__contacts_array_message__pack_to_buffer
                     (const Proto__ContactsArrayMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__ContactsArrayMessage *
       proto__contacts_array_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__contacts_array_message__free_unpacked
                     (Proto__ContactsArrayMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__HSMCurrency methods */
void   proto__hsmcurrency__init
                     (Proto__HSMCurrency         *message);
size_t proto__hsmcurrency__get_packed_size
                     (const Proto__HSMCurrency   *message);
size_t proto__hsmcurrency__pack
                     (const Proto__HSMCurrency   *message,
                      uint8_t             *out);
size_t proto__hsmcurrency__pack_to_buffer
                     (const Proto__HSMCurrency   *message,
                      ProtobufCBuffer     *buffer);
Proto__HSMCurrency *
       proto__hsmcurrency__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__hsmcurrency__free_unpacked
                     (Proto__HSMCurrency *message,
                      ProtobufCAllocator *allocator);
/* Proto__HSMDateTimeComponent methods */
void   proto__hsmdate_time_component__init
                     (Proto__HSMDateTimeComponent         *message);
size_t proto__hsmdate_time_component__get_packed_size
                     (const Proto__HSMDateTimeComponent   *message);
size_t proto__hsmdate_time_component__pack
                     (const Proto__HSMDateTimeComponent   *message,
                      uint8_t             *out);
size_t proto__hsmdate_time_component__pack_to_buffer
                     (const Proto__HSMDateTimeComponent   *message,
                      ProtobufCBuffer     *buffer);
Proto__HSMDateTimeComponent *
       proto__hsmdate_time_component__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__hsmdate_time_component__free_unpacked
                     (Proto__HSMDateTimeComponent *message,
                      ProtobufCAllocator *allocator);
/* Proto__HSMDateTimeUnixEpoch methods */
void   proto__hsmdate_time_unix_epoch__init
                     (Proto__HSMDateTimeUnixEpoch         *message);
size_t proto__hsmdate_time_unix_epoch__get_packed_size
                     (const Proto__HSMDateTimeUnixEpoch   *message);
size_t proto__hsmdate_time_unix_epoch__pack
                     (const Proto__HSMDateTimeUnixEpoch   *message,
                      uint8_t             *out);
size_t proto__hsmdate_time_unix_epoch__pack_to_buffer
                     (const Proto__HSMDateTimeUnixEpoch   *message,
                      ProtobufCBuffer     *buffer);
Proto__HSMDateTimeUnixEpoch *
       proto__hsmdate_time_unix_epoch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__hsmdate_time_unix_epoch__free_unpacked
                     (Proto__HSMDateTimeUnixEpoch *message,
                      ProtobufCAllocator *allocator);
/* Proto__HSMDateTime methods */
void   proto__hsmdate_time__init
                     (Proto__HSMDateTime         *message);
size_t proto__hsmdate_time__get_packed_size
                     (const Proto__HSMDateTime   *message);
size_t proto__hsmdate_time__pack
                     (const Proto__HSMDateTime   *message,
                      uint8_t             *out);
size_t proto__hsmdate_time__pack_to_buffer
                     (const Proto__HSMDateTime   *message,
                      ProtobufCBuffer     *buffer);
Proto__HSMDateTime *
       proto__hsmdate_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__hsmdate_time__free_unpacked
                     (Proto__HSMDateTime *message,
                      ProtobufCAllocator *allocator);
/* Proto__HSMLocalizableParameter methods */
void   proto__hsmlocalizable_parameter__init
                     (Proto__HSMLocalizableParameter         *message);
size_t proto__hsmlocalizable_parameter__get_packed_size
                     (const Proto__HSMLocalizableParameter   *message);
size_t proto__hsmlocalizable_parameter__pack
                     (const Proto__HSMLocalizableParameter   *message,
                      uint8_t             *out);
size_t proto__hsmlocalizable_parameter__pack_to_buffer
                     (const Proto__HSMLocalizableParameter   *message,
                      ProtobufCBuffer     *buffer);
Proto__HSMLocalizableParameter *
       proto__hsmlocalizable_parameter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__hsmlocalizable_parameter__free_unpacked
                     (Proto__HSMLocalizableParameter *message,
                      ProtobufCAllocator *allocator);
/* Proto__HighlyStructuredMessage methods */
void   proto__highly_structured_message__init
                     (Proto__HighlyStructuredMessage         *message);
size_t proto__highly_structured_message__get_packed_size
                     (const Proto__HighlyStructuredMessage   *message);
size_t proto__highly_structured_message__pack
                     (const Proto__HighlyStructuredMessage   *message,
                      uint8_t             *out);
size_t proto__highly_structured_message__pack_to_buffer
                     (const Proto__HighlyStructuredMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__HighlyStructuredMessage *
       proto__highly_structured_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__highly_structured_message__free_unpacked
                     (Proto__HighlyStructuredMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__SendPaymentMessage methods */
void   proto__send_payment_message__init
                     (Proto__SendPaymentMessage         *message);
size_t proto__send_payment_message__get_packed_size
                     (const Proto__SendPaymentMessage   *message);
size_t proto__send_payment_message__pack
                     (const Proto__SendPaymentMessage   *message,
                      uint8_t             *out);
size_t proto__send_payment_message__pack_to_buffer
                     (const Proto__SendPaymentMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__SendPaymentMessage *
       proto__send_payment_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__send_payment_message__free_unpacked
                     (Proto__SendPaymentMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__RequestPaymentMessage methods */
void   proto__request_payment_message__init
                     (Proto__RequestPaymentMessage         *message);
size_t proto__request_payment_message__get_packed_size
                     (const Proto__RequestPaymentMessage   *message);
size_t proto__request_payment_message__pack
                     (const Proto__RequestPaymentMessage   *message,
                      uint8_t             *out);
size_t proto__request_payment_message__pack_to_buffer
                     (const Proto__RequestPaymentMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__RequestPaymentMessage *
       proto__request_payment_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__request_payment_message__free_unpacked
                     (Proto__RequestPaymentMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__LiveLocationMessage methods */
void   proto__live_location_message__init
                     (Proto__LiveLocationMessage         *message);
size_t proto__live_location_message__get_packed_size
                     (const Proto__LiveLocationMessage   *message);
size_t proto__live_location_message__pack
                     (const Proto__LiveLocationMessage   *message,
                      uint8_t             *out);
size_t proto__live_location_message__pack_to_buffer
                     (const Proto__LiveLocationMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__LiveLocationMessage *
       proto__live_location_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__live_location_message__free_unpacked
                     (Proto__LiveLocationMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__StickerMessage methods */
void   proto__sticker_message__init
                     (Proto__StickerMessage         *message);
size_t proto__sticker_message__get_packed_size
                     (const Proto__StickerMessage   *message);
size_t proto__sticker_message__pack
                     (const Proto__StickerMessage   *message,
                      uint8_t             *out);
size_t proto__sticker_message__pack_to_buffer
                     (const Proto__StickerMessage   *message,
                      ProtobufCBuffer     *buffer);
Proto__StickerMessage *
       proto__sticker_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__sticker_message__free_unpacked
                     (Proto__StickerMessage *message,
                      ProtobufCAllocator *allocator);
/* Proto__Message methods */
void   proto__message__init
                     (Proto__Message         *message);
size_t proto__message__get_packed_size
                     (const Proto__Message   *message);
size_t proto__message__pack
                     (const Proto__Message   *message,
                      uint8_t             *out);
size_t proto__message__pack_to_buffer
                     (const Proto__Message   *message,
                      ProtobufCBuffer     *buffer);
Proto__Message *
       proto__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__message__free_unpacked
                     (Proto__Message *message,
                      ProtobufCAllocator *allocator);
/* Proto__ContextInfo methods */
void   proto__context_info__init
                     (Proto__ContextInfo         *message);
size_t proto__context_info__get_packed_size
                     (const Proto__ContextInfo   *message);
size_t proto__context_info__pack
                     (const Proto__ContextInfo   *message,
                      uint8_t             *out);
size_t proto__context_info__pack_to_buffer
                     (const Proto__ContextInfo   *message,
                      ProtobufCBuffer     *buffer);
Proto__ContextInfo *
       proto__context_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__context_info__free_unpacked
                     (Proto__ContextInfo *message,
                      ProtobufCAllocator *allocator);
/* Proto__InteractiveAnnotation methods */
void   proto__interactive_annotation__init
                     (Proto__InteractiveAnnotation         *message);
size_t proto__interactive_annotation__get_packed_size
                     (const Proto__InteractiveAnnotation   *message);
size_t proto__interactive_annotation__pack
                     (const Proto__InteractiveAnnotation   *message,
                      uint8_t             *out);
size_t proto__interactive_annotation__pack_to_buffer
                     (const Proto__InteractiveAnnotation   *message,
                      ProtobufCBuffer     *buffer);
Proto__InteractiveAnnotation *
       proto__interactive_annotation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__interactive_annotation__free_unpacked
                     (Proto__InteractiveAnnotation *message,
                      ProtobufCAllocator *allocator);
/* Proto__Point methods */
void   proto__point__init
                     (Proto__Point         *message);
size_t proto__point__get_packed_size
                     (const Proto__Point   *message);
size_t proto__point__pack
                     (const Proto__Point   *message,
                      uint8_t             *out);
size_t proto__point__pack_to_buffer
                     (const Proto__Point   *message,
                      ProtobufCBuffer     *buffer);
Proto__Point *
       proto__point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__point__free_unpacked
                     (Proto__Point *message,
                      ProtobufCAllocator *allocator);
/* Proto__Location methods */
void   proto__location__init
                     (Proto__Location         *message);
size_t proto__location__get_packed_size
                     (const Proto__Location   *message);
size_t proto__location__pack
                     (const Proto__Location   *message,
                      uint8_t             *out);
size_t proto__location__pack_to_buffer
                     (const Proto__Location   *message,
                      ProtobufCBuffer     *buffer);
Proto__Location *
       proto__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__location__free_unpacked
                     (Proto__Location *message,
                      ProtobufCAllocator *allocator);
/* Proto__WebMessageInfo methods */
void   proto__web_message_info__init
                     (Proto__WebMessageInfo         *message);
size_t proto__web_message_info__get_packed_size
                     (const Proto__WebMessageInfo   *message);
size_t proto__web_message_info__pack
                     (const Proto__WebMessageInfo   *message,
                      uint8_t             *out);
size_t proto__web_message_info__pack_to_buffer
                     (const Proto__WebMessageInfo   *message,
                      ProtobufCBuffer     *buffer);
Proto__WebMessageInfo *
       proto__web_message_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__web_message_info__free_unpacked
                     (Proto__WebMessageInfo *message,
                      ProtobufCAllocator *allocator);
/* Proto__WebNotificationsInfo methods */
void   proto__web_notifications_info__init
                     (Proto__WebNotificationsInfo         *message);
size_t proto__web_notifications_info__get_packed_size
                     (const Proto__WebNotificationsInfo   *message);
size_t proto__web_notifications_info__pack
                     (const Proto__WebNotificationsInfo   *message,
                      uint8_t             *out);
size_t proto__web_notifications_info__pack_to_buffer
                     (const Proto__WebNotificationsInfo   *message,
                      ProtobufCBuffer     *buffer);
Proto__WebNotificationsInfo *
       proto__web_notifications_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__web_notifications_info__free_unpacked
                     (Proto__WebNotificationsInfo *message,
                      ProtobufCAllocator *allocator);
/* Proto__NotificationMessageInfo methods */
void   proto__notification_message_info__init
                     (Proto__NotificationMessageInfo         *message);
size_t proto__notification_message_info__get_packed_size
                     (const Proto__NotificationMessageInfo   *message);
size_t proto__notification_message_info__pack
                     (const Proto__NotificationMessageInfo   *message,
                      uint8_t             *out);
size_t proto__notification_message_info__pack_to_buffer
                     (const Proto__NotificationMessageInfo   *message,
                      ProtobufCBuffer     *buffer);
Proto__NotificationMessageInfo *
       proto__notification_message_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__notification_message_info__free_unpacked
                     (Proto__NotificationMessageInfo *message,
                      ProtobufCAllocator *allocator);
/* Proto__TabletNotificationsInfo methods */
void   proto__tablet_notifications_info__init
                     (Proto__TabletNotificationsInfo         *message);
size_t proto__tablet_notifications_info__get_packed_size
                     (const Proto__TabletNotificationsInfo   *message);
size_t proto__tablet_notifications_info__pack
                     (const Proto__TabletNotificationsInfo   *message,
                      uint8_t             *out);
size_t proto__tablet_notifications_info__pack_to_buffer
                     (const Proto__TabletNotificationsInfo   *message,
                      ProtobufCBuffer     *buffer);
Proto__TabletNotificationsInfo *
       proto__tablet_notifications_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__tablet_notifications_info__free_unpacked
                     (Proto__TabletNotificationsInfo *message,
                      ProtobufCAllocator *allocator);
/* Proto__WebFeatures methods */
void   proto__web_features__init
                     (Proto__WebFeatures         *message);
size_t proto__web_features__get_packed_size
                     (const Proto__WebFeatures   *message);
size_t proto__web_features__pack
                     (const Proto__WebFeatures   *message,
                      uint8_t             *out);
size_t proto__web_features__pack_to_buffer
                     (const Proto__WebFeatures   *message,
                      ProtobufCBuffer     *buffer);
Proto__WebFeatures *
       proto__web_features__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__web_features__free_unpacked
                     (Proto__WebFeatures *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__FingerprintData_Closure)
                 (const Proto__FingerprintData *message,
                  void *closure_data);
typedef void (*Proto__CombinedFingerprint_Closure)
                 (const Proto__CombinedFingerprint *message,
                  void *closure_data);
typedef void (*Proto__MessageKey_Closure)
                 (const Proto__MessageKey *message,
                  void *closure_data);
typedef void (*Proto__SenderKeyDistributionMessage_Closure)
                 (const Proto__SenderKeyDistributionMessage *message,
                  void *closure_data);
typedef void (*Proto__ImageMessage_Closure)
                 (const Proto__ImageMessage *message,
                  void *closure_data);
typedef void (*Proto__ContactMessage_Closure)
                 (const Proto__ContactMessage *message,
                  void *closure_data);
typedef void (*Proto__LocationMessage_Closure)
                 (const Proto__LocationMessage *message,
                  void *closure_data);
typedef void (*Proto__ExtendedTextMessage_Closure)
                 (const Proto__ExtendedTextMessage *message,
                  void *closure_data);
typedef void (*Proto__DocumentMessage_Closure)
                 (const Proto__DocumentMessage *message,
                  void *closure_data);
typedef void (*Proto__AudioMessage_Closure)
                 (const Proto__AudioMessage *message,
                  void *closure_data);
typedef void (*Proto__VideoMessage_Closure)
                 (const Proto__VideoMessage *message,
                  void *closure_data);
typedef void (*Proto__Call_Closure)
                 (const Proto__Call *message,
                  void *closure_data);
typedef void (*Proto__Chat_Closure)
                 (const Proto__Chat *message,
                  void *closure_data);
typedef void (*Proto__ProtocolMessage_Closure)
                 (const Proto__ProtocolMessage *message,
                  void *closure_data);
typedef void (*Proto__ContactsArrayMessage_Closure)
                 (const Proto__ContactsArrayMessage *message,
                  void *closure_data);
typedef void (*Proto__HSMCurrency_Closure)
                 (const Proto__HSMCurrency *message,
                  void *closure_data);
typedef void (*Proto__HSMDateTimeComponent_Closure)
                 (const Proto__HSMDateTimeComponent *message,
                  void *closure_data);
typedef void (*Proto__HSMDateTimeUnixEpoch_Closure)
                 (const Proto__HSMDateTimeUnixEpoch *message,
                  void *closure_data);
typedef void (*Proto__HSMDateTime_Closure)
                 (const Proto__HSMDateTime *message,
                  void *closure_data);
typedef void (*Proto__HSMLocalizableParameter_Closure)
                 (const Proto__HSMLocalizableParameter *message,
                  void *closure_data);
typedef void (*Proto__HighlyStructuredMessage_Closure)
                 (const Proto__HighlyStructuredMessage *message,
                  void *closure_data);
typedef void (*Proto__SendPaymentMessage_Closure)
                 (const Proto__SendPaymentMessage *message,
                  void *closure_data);
typedef void (*Proto__RequestPaymentMessage_Closure)
                 (const Proto__RequestPaymentMessage *message,
                  void *closure_data);
typedef void (*Proto__LiveLocationMessage_Closure)
                 (const Proto__LiveLocationMessage *message,
                  void *closure_data);
typedef void (*Proto__StickerMessage_Closure)
                 (const Proto__StickerMessage *message,
                  void *closure_data);
typedef void (*Proto__Message_Closure)
                 (const Proto__Message *message,
                  void *closure_data);
typedef void (*Proto__ContextInfo_Closure)
                 (const Proto__ContextInfo *message,
                  void *closure_data);
typedef void (*Proto__InteractiveAnnotation_Closure)
                 (const Proto__InteractiveAnnotation *message,
                  void *closure_data);
typedef void (*Proto__Point_Closure)
                 (const Proto__Point *message,
                  void *closure_data);
typedef void (*Proto__Location_Closure)
                 (const Proto__Location *message,
                  void *closure_data);
typedef void (*Proto__WebMessageInfo_Closure)
                 (const Proto__WebMessageInfo *message,
                  void *closure_data);
typedef void (*Proto__WebNotificationsInfo_Closure)
                 (const Proto__WebNotificationsInfo *message,
                  void *closure_data);
typedef void (*Proto__NotificationMessageInfo_Closure)
                 (const Proto__NotificationMessageInfo *message,
                  void *closure_data);
typedef void (*Proto__TabletNotificationsInfo_Closure)
                 (const Proto__TabletNotificationsInfo *message,
                  void *closure_data);
typedef void (*Proto__WebFeatures_Closure)
                 (const Proto__WebFeatures *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__fingerprint_data__descriptor;
extern const ProtobufCMessageDescriptor proto__combined_fingerprint__descriptor;
extern const ProtobufCMessageDescriptor proto__message_key__descriptor;
extern const ProtobufCMessageDescriptor proto__sender_key_distribution_message__descriptor;
extern const ProtobufCMessageDescriptor proto__image_message__descriptor;
extern const ProtobufCMessageDescriptor proto__contact_message__descriptor;
extern const ProtobufCMessageDescriptor proto__location_message__descriptor;
extern const ProtobufCMessageDescriptor proto__extended_text_message__descriptor;
extern const ProtobufCEnumDescriptor    proto__extended_text_message__fonttype__descriptor;
extern const ProtobufCMessageDescriptor proto__document_message__descriptor;
extern const ProtobufCMessageDescriptor proto__audio_message__descriptor;
extern const ProtobufCMessageDescriptor proto__video_message__descriptor;
extern const ProtobufCEnumDescriptor    proto__video_message__attribution__descriptor;
extern const ProtobufCMessageDescriptor proto__call__descriptor;
extern const ProtobufCMessageDescriptor proto__chat__descriptor;
extern const ProtobufCMessageDescriptor proto__protocol_message__descriptor;
extern const ProtobufCEnumDescriptor    proto__protocol_message__type__descriptor;
extern const ProtobufCMessageDescriptor proto__contacts_array_message__descriptor;
extern const ProtobufCMessageDescriptor proto__hsmcurrency__descriptor;
extern const ProtobufCMessageDescriptor proto__hsmdate_time_component__descriptor;
extern const ProtobufCEnumDescriptor    proto__hsmdate_time_component__dayofweektype__descriptor;
extern const ProtobufCEnumDescriptor    proto__hsmdate_time_component__calendartype__descriptor;
extern const ProtobufCMessageDescriptor proto__hsmdate_time_unix_epoch__descriptor;
extern const ProtobufCMessageDescriptor proto__hsmdate_time__descriptor;
extern const ProtobufCMessageDescriptor proto__hsmlocalizable_parameter__descriptor;
extern const ProtobufCMessageDescriptor proto__highly_structured_message__descriptor;
extern const ProtobufCMessageDescriptor proto__send_payment_message__descriptor;
extern const ProtobufCMessageDescriptor proto__request_payment_message__descriptor;
extern const ProtobufCMessageDescriptor proto__live_location_message__descriptor;
extern const ProtobufCMessageDescriptor proto__sticker_message__descriptor;
extern const ProtobufCMessageDescriptor proto__message__descriptor;
extern const ProtobufCMessageDescriptor proto__context_info__descriptor;
extern const ProtobufCMessageDescriptor proto__interactive_annotation__descriptor;
extern const ProtobufCMessageDescriptor proto__point__descriptor;
extern const ProtobufCMessageDescriptor proto__location__descriptor;
extern const ProtobufCMessageDescriptor proto__web_message_info__descriptor;
extern const ProtobufCEnumDescriptor    proto__web_message_info__status__descriptor;
extern const ProtobufCEnumDescriptor    proto__web_message_info__stubtype__descriptor;
extern const ProtobufCMessageDescriptor proto__web_notifications_info__descriptor;
extern const ProtobufCMessageDescriptor proto__notification_message_info__descriptor;
extern const ProtobufCMessageDescriptor proto__tablet_notifications_info__descriptor;
extern const ProtobufCMessageDescriptor proto__web_features__descriptor;
extern const ProtobufCEnumDescriptor    proto__web_features__flag__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_pmsg_2eproto__INCLUDED */
